### ISSUE TITLE
Using the same nodes (A -> B) twice overrides the last one

### ISSUE THREAD

**Issue by LuisDavidR** [fisharebest/algorithm#2]
Hi, I added two nodes with the same points and the first one gets override by the second.

A->B, cost 5
A->B, cost 10

This library doesn't keep both options, it just discard the first combination (A->B, cost 5).
Is there a way to change this? I need both options.

Thanks in advance,
Luís Rodrigues

**Comment by nemeth-it** [comment]
And why you've closed your issue?
