### ISSUE TITLE
Customize comparison between tokens in MyersDiff

### ISSUE THREAD

**Issue by grillonbleu** [fisharebest/algorithm#7]
What would be an optimal strategy to define a different definition of equality between tokens in MyersDiff? If I understand well, the comparing itself happens on [line 144](https://github.com/fisharebest/algorithm/blob/master/src/MyersDiff.php#L144). Since the === operator can’t be overloaded, I’m somewhat at a loss. Would you be interested in a PR that may take an optional comparison function?

**Comment by fisharebest** [comment]
> Would you be interested in a PR that may take an optional comparison function?

I guess you mean something like this.

```
public function calculate(array $a, array $b, $compare=null)
{
  if ($compare === null) {
    $compare = static function ($x, $y) { return $x === $y; };
  }

  ... && compare($a[$x], $b[$y]) ...


}
```

Sure!  Go ahead.

**Comment by fisharebest** [comment]
Thanks for the PR.  I will tag this as `1.6.0`.

But first, I need to update the project configuration.  e.g. replace Travis-CI with Github actions, etc.
